### ISSUE TITLE
VerifyError: Error #1014: Class mx.core::DebuggableWorker could not be found.

### ISSUE THREAD

**Issue by timoisalive** [doublefx/easyWorker#10]
Hi,
I tried using the pure as3 branch, but still got this error. Isn't this a Flex related class?
Cheers,
Timo

**Comment by doublefx** [comment]
Hi,


Yes it is, you need to create a flex as3 only project,  it will include only the core classes you will need,  apparently only thiw one,  another option is to monkey patch this class into your project.


HTH


Envoyé avec Outlook pour Android





On Thu, Oct 1, 2015 at 7:09 AM -0700, "timoisalive" <notifications@github.com> wrote:
Hi,
I tried using the pure as3 branch, but still got this error. Isn't this a Flex related class?
Cheers,
Timo

---
Reply to this email directly or view it on GitHub:
https://github.com/doublefx/easyWorker/issues/10

**Comment by timoisalive** [comment]
Ok, thanks, I thought it didn't need Flex at all..

One more question, is this technique compatible with the iOS concurrency requirements also?

**Comment by doublefx** [comment]
I hadn't got the opportunity to try against ios yet but except if you can point out something that shows the workers work differently on it,  I could try blindly to adapt it.


Envoyé avec Outlook pour Android





On Fri, Oct 2, 2015 at 12:03 AM -0700, "timoisalive" <notifications@github.com> wrote:
Ok, thanks, I thought it didn't need Flex at all..

One more question, is this technique compatible with the iOS concurrency requirements also?

---

**Comment by timoisalive** [comment]
The AIR 19 release notes reads:

Everything remains coherent to AIR Android except for differences in loading of swf and passing byte array to worker.
1. As dynamically loading a ‘remote‘ SWF that contains ActionScript code doesn't work. Remote swf have to be passed to worker as stripped swf.
2. Embedding SWFs(having ABC code) using [Embed] tag will not work on iOS.

I assume this is not a problem in easyWorker though...

I ended up using the standard way to create workers for now at least, the missing Flex classes stopped me trying out easyWorker.. :)
