### ISSUE TITLE
Passed argument can't cast 

### ISSUE THREAD

**Issue by varadig** [doublefx/easyWorker#12]
In your sample there is a TermVo.
But If I pass this value object:

    _thread.start(new TermsVo(1,2));

and in the worker try to cast the args[0] to TermsVo:

    const values:TermsVo = args[0] as TermsVo;

the values is equal to null.

with hard casting?
   
    const values:TermsVo = TermsVo(args[0]);
   
    ThreadRunner dispatchError: Error #1034: Type Coercion failed: cannot convert Object@95223d1 to workers.vo.TermsVo.

What I do wrong?

**Comment by varadig** [comment]
I tried a followings:

   trace(getQualifiedClassName(args[0])); //Object

How can I pass a non primitive object?
If I pass (Number,int,String.....etc.) primitive types, that work fine.
I missing something?

**Comment by doublefx** [comment]
Hi Varadig, sorry for the delay, I just got back my computer working today and get a lot to catch up, I will try to have a look at this before Sunday though.

**Comment by varadig** [comment]
Hi Doublefx,

could you check the issue?

thanks
Gábor

**Comment by doublefx** [comment]
The last version was working for me, anyway, there is a new one if you like to try it, maybe you forgot to pass the compiler argument -optimize=false ?

**Comment by varadig** [comment]
Thanks it's work!
