### ISSUE TITLE
Published application Issues

### ISSUE THREAD

**Issue by polar1225** [doublefx/easyWorker#13]
Hi Frédéric
I got the same issuse as this post:https://github.com/doublefx/easyWorker/issues/3
I can get it worked by adding the compiler option -optimize=false,By I want to optimize the swf by the complier.So I change the code in Thread.as: 
             const file:FileReference = new FileReference();
             file.save(swfBytes, "Worker.swf");
Save the swf in debug mode.Embed the swf.
create the worker by swf bytes:_worker = createWorkerFromSWF(swfBytes,workerDomain);
But it does not work in release version,
Any Idea? Thanks..

**Comment by doublefx** [comment]
If you give me the small project that demonstrates what you are saying, I could have look.

**Comment by polar1225** [comment]
General speaking,i save the swf created by as3swf in debug mode.Create the thread worker by this swf instead.It seems like threads are never responding in publish application..

**Comment by doublefx** [comment]
Indeed, it won't work like that as the application has not set all the shared properties and message channels that easyworker provides.

But if your use case is to create a Worker with easyWorker, save it as swf, then eventually use the optimizer on it, embed it or load it into another application and call the flash.system.Worker.createWorker to use it, I guess you can extend Thread, override the constructor to plug the optimized worker with the easyWorker shared properties and message channels, just remove the call to the reflection parts and createWorkerFromSWF.

Does it make sense ?
