### ISSUE TITLE
Posted download link for swc is broken

### ISSUE THREAD

**Issue by Ansury** [doublefx/easyWorker#7]
Broken link: 
http://www.sharebeast.com/er9n45ly0s8c

**Comment by 4xy** [comment]
Please, give us the correct one

**Comment by Ansury** [comment]
Links still broken...  Would be nice if the external sharebeast links could just be added to the repo here - they shouldn't be too big.

**Comment by polar1225** [comment]
http://www.sharebeast.com/940onmjnfsws
Links is still broken..Maybe u can use a stable Cloud instead

**Comment by smorales** [comment]
The link is broken: http://www.sharebeast.com/940onmjnfsws

**Comment by GhaziTriki** [comment]
@doublefx can you please provied another download link?

**Comment by doublefx** [comment]
https://github.com/doublefx/easyWorker/blob/master/debug/easyWorker.swc
https://github.com/doublefx/easyWorker/blob/PureAS3/debug/easyWorkerAS3.swc
